server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://cdb-o742k9kc.bj.tencentcdb.com:10035/app?useUnicode=true&characterEncoding=utf-8&useSSL=false
swagger:
  serviceName: app
  description: api说明文档
  developer: mapper
  url:
  email: 547008022@qq.com