server:
  port: 8081

spring:
  application:
    name: s1
  datasource:
#    name: test
    url: jdbc:mysql://cdb-o742k9kc.bj.tencentcdb.com:10035/app?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mapper321
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 106.12.11.4
    port: 6379
    password: bkcc2018
  data:
    mongodb:
      host: 106.12.11.4
      port: 27017
      database: app
mybatis:
  mapper-locations: classpath*:com/hebei/*/*/data/*.map.xml
  typeAliasesPackage: com.hebei.*.*.data

logging:
  config: classpath:logback-spring.xml

#springfox:
#  documentation:
#    swagger:
#      v2:
#        host: 140.143.35.107:8081

swagger:
  serviceName: app
  description: api说明文档
  developer: mapper
  url:
  email: 547008022@qq.com

eureka:
  instance:
    prefer-ip-address: true
#    续约时间和超时设置
#    lease-renewal-interval-in-seconds: 3
#    lease-expiration-duration-in-seconds: 9
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5